using System.Net;
using System.Text;
using JobRadar.Core.Models;

namespace JobRadar.Notify;

public static class DigestRenderer
{
    public static string BuildSubject(IReadOnlyList<DigestEntry> entries)
    {
        var top = entries.Count == 0 ? 0 : entries.Max(e => e.Score.MatchScore);
        return $"[job-radar] {entries.Count} new postings — {top} top match";
    }

    public static string BuildHtml(IReadOnlyList<DigestEntry> entries, DateTimeOffset generatedAt)
    {
        var grouped = entries
            .GroupBy(e => e.Band)
            .ToDictionary(g => g.Key, g => g.OrderByDescending(e => e.Score.MatchScore).ToList());

        var sb = new StringBuilder();
        sb.Append("""
            <!doctype html><html><head><meta charset="utf-8"><title>job-radar daily digest</title></head>
            <body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;color:#1a1a1a;max-width:760px;margin:0 auto;padding:24px;background:#fafafa;">
            """);

        sb.Append($"""<h1 style="font-size:20px;margin:0 0 16px 0;">job-radar — {entries.Count} postings, {generatedAt:yyyy-MM-dd HH:mm} UTC</h1>""");

        AppendSection(sb, "⭐ Top matches (8–10)", grouped.GetValueOrDefault(ScoreBand.Top), "#1f7a3d");
        AppendSection(sb, "✅ Worth a look (5–7)", grouped.GetValueOrDefault(ScoreBand.WorthALook), "#1a5fb4");
        AppendSection(sb, "📋 Sanity check (1–4)", grouped.GetValueOrDefault(ScoreBand.SanityCheck), "#666666");

        sb.Append("""
            <p style="font-size:11px;color:#888;margin-top:24px;">Generated by job-radar. Reply to this email to flag bad matches; tune filters in <code>config/filters.yml</code>.</p>
            </body></html>
            """);
        return sb.ToString();
    }

    private static void AppendSection(StringBuilder sb, string heading, List<DigestEntry>? entries, string color)
    {
        if (entries is null || entries.Count == 0) return;
        sb.Append($"""<h2 style="font-size:16px;color:{color};border-bottom:1px solid #ddd;padding-bottom:4px;margin-top:24px;">{heading} ({entries.Count})</h2>""");
        foreach (var e in entries)
        {
            sb.Append(RenderEntry(e));
        }
    }

    private static string RenderEntry(DigestEntry e)
    {
        var ambiguous = e.Score.Eligibility == EligibilityVerdict.Ambiguous;
        var border = ambiguous ? "#f0ad4e" : "#e2e2e2";
        var ambBadge = ambiguous ? """ <span style="background:#fbe8c8;color:#7a4a00;font-size:10px;padding:1px 6px;border-radius:3px;margin-left:6px;">eligibility unclear</span>""" : string.Empty;
        var salary = string.IsNullOrEmpty(e.Score.SalaryListed)
            ? string.Empty
            : $""" · <span style="color:#1f7a3d;">💶 {Esc(e.Score.SalaryListed)}</span>""";

        var sb = new StringBuilder();
        sb.Append($"""<div style="background:#fff;border:1px solid {border};border-radius:6px;padding:14px;margin:10px 0;">""");
        sb.Append($"""<div style="display:flex;align-items:baseline;justify-content:space-between;gap:12px;">""");
        sb.Append($"""<div style="font-size:15px;font-weight:600;"><a href="{Esc(e.Posting.Url)}" style="color:#0b5ed7;text-decoration:none;">{Esc(e.Posting.Title)}</a>{ambBadge}</div>""");
        sb.Append($"""<div style="font-size:18px;font-weight:700;color:#1a5fb4;">{e.Score.MatchScore}/10</div>""");
        sb.Append("</div>");
        sb.Append($"""<div style="font-size:13px;color:#555;margin-top:4px;">{Esc(e.Posting.Company)} · {Esc(e.Posting.Location)} · <span style="text-transform:capitalize;">{Esc(e.Score.RemotePolicy ?? "?")}</span> · <span style="color:#888;">{Esc(e.Posting.Source)}</span>{salary}</div>""");
        if (!string.IsNullOrEmpty(e.Score.OneLinePitch))
        {
            sb.Append($"""<div style="margin-top:8px;font-size:13px;line-height:1.4;">{Esc(e.Score.OneLinePitch)}</div>""");
        }
        if (!string.IsNullOrEmpty(e.Score.TopConcern))
        {
            sb.Append($"""<div style="margin-top:6px;font-size:12px;color:#7a4a00;"><strong>Concern:</strong> {Esc(e.Score.TopConcern)}</div>""");
        }
        sb.Append("</div>");
        return sb.ToString();
    }

    private static string Esc(string? s) => string.IsNullOrEmpty(s) ? string.Empty : WebUtility.HtmlEncode(s);
}
