using System.Net;
using System.Text;
using JobRadar.Core.Models;

namespace JobRadar.Notify;

public static class DigestRenderer
{
    public static string BuildSubject(IReadOnlyList<DigestEntry> entries, DateTimeOffset generatedAt)
    {
        if (entries.Count == 0)
        {
            return "[job-radar] 0 new postings";
        }

        var top = entries.Max(e => e.Score.MatchScore);
        var pending = entries.Count(e => e.IsCarryOver(generatedAt));
        var fresh = entries.Count - pending;

        return pending > 0
            ? $"[job-radar] {entries.Count} postings ({fresh} new, {pending} pending) — {top} top match"
            : $"[job-radar] {entries.Count} new postings — {top} top match";
    }

    // Back-compat wrapper for tests/callers that don't pass a clock.
    public static string BuildSubject(IReadOnlyList<DigestEntry> entries) =>
        BuildSubject(entries, DateTimeOffset.UtcNow);

    public static string BuildHtml(IReadOnlyList<DigestEntry> entries, DateTimeOffset generatedAt)
    {
        var grouped = entries
            .GroupBy(e => e.Band)
            .ToDictionary(g => g.Key, g => g.OrderByDescending(e => e.Score.MatchScore).ToList());

        var sb = new StringBuilder();
        sb.Append("""
            <!doctype html><html><head><meta charset="utf-8"><title>job-radar daily digest</title></head>
            <body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;color:#1a1a1a;max-width:760px;margin:0 auto;padding:24px;background:#fafafa;">
            """);

        sb.Append($"""<h1 style="font-size:20px;margin:0 0 16px 0;">job-radar — {entries.Count} postings, {generatedAt:yyyy-MM-dd HH:mm} UTC</h1>""");

        AppendSection(sb, "⭐ Top matches (8–10)", grouped.GetValueOrDefault(ScoreBand.Top), "#1f7a3d", generatedAt);
        AppendSection(sb, "✅ Worth a look (5–7)", grouped.GetValueOrDefault(ScoreBand.WorthALook), "#1a5fb4", generatedAt);
        AppendSection(sb, "📋 Sanity check (1–4)", grouped.GetValueOrDefault(ScoreBand.SanityCheck), "#666666", generatedAt);

        sb.Append("""
            <p style="font-size:11px;color:#888;margin-top:24px;">Generated by job-radar. To remove a posting, run <code>dotnet run -- --mark-applied &lt;url&gt;</code> or <code>--dismiss &lt;url&gt;</code> (or edit <code>data/applied.yml</code>).</p>
            </body></html>
            """);
        return sb.ToString();
    }

    private static void AppendSection(StringBuilder sb, string heading, List<DigestEntry>? entries, string color, DateTimeOffset generatedAt)
    {
        if (entries is null || entries.Count == 0) return;
        sb.Append($"""<h2 style="font-size:16px;color:{color};border-bottom:1px solid #ddd;padding-bottom:4px;margin-top:24px;">{heading} ({entries.Count})</h2>""");
        foreach (var e in entries)
        {
            sb.Append(RenderEntry(e, generatedAt));
        }
    }

    private static string RenderEntry(DigestEntry e, DateTimeOffset generatedAt)
    {
        var ambiguous = e.Score.Eligibility == EligibilityVerdict.Ambiguous;
        var border = ambiguous ? "#f0ad4e" : "#e2e2e2";
        var ambBadge = ambiguous ? """ <span style="background:#fbe8c8;color:#7a4a00;font-size:10px;padding:1px 6px;border-radius:3px;margin-left:6px;">eligibility unclear</span>""" : string.Empty;
        var pendingBadge = e.IsCarryOver(generatedAt)
            ? $""" <span style="background:#e6e6fa;color:#42397a;font-size:10px;padding:1px 6px;border-radius:3px;margin-left:6px;">pending since {e.FirstSeenAt:MMM d}</span>"""
            : string.Empty;
        var salary = string.IsNullOrEmpty(e.Score.SalaryListed)
            ? string.Empty
            : $""" · <span style="color:#1f7a3d;">💶 {Esc(e.Score.SalaryListed)}</span>""";

        var sb = new StringBuilder();
        sb.Append($"""<div style="background:#fff;border:1px solid {border};border-radius:6px;padding:14px;margin:10px 0;">""");
        sb.Append($"""<div style="display:flex;align-items:baseline;justify-content:space-between;gap:12px;">""");
        sb.Append($"""<div style="font-size:15px;font-weight:600;"><a href="{Esc(e.Posting.Url)}" style="color:#0b5ed7;text-decoration:none;">{Esc(e.Posting.Title)}</a>{ambBadge}{pendingBadge}</div>""");
        sb.Append($"""<div style="font-size:18px;font-weight:700;color:#1a5fb4;">{e.Score.MatchScore}/10</div>""");
        sb.Append("</div>");
        sb.Append($"""<div style="font-size:13px;color:#555;margin-top:4px;">{Esc(e.Posting.Company)} · {Esc(e.Posting.Location)} · <span style="text-transform:capitalize;">{Esc(e.Score.RemotePolicy ?? "?")}</span> · <span style="color:#888;">{Esc(e.Posting.Source)}</span>{salary}</div>""");
        if (!string.IsNullOrEmpty(e.Score.OneLinePitch))
        {
            sb.Append($"""<div style="margin-top:8px;font-size:13px;line-height:1.4;">{Esc(e.Score.OneLinePitch)}</div>""");
        }
        if (!string.IsNullOrEmpty(e.Score.TopConcern))
        {
            sb.Append($"""<div style="margin-top:6px;font-size:12px;color:#7a4a00;"><strong>Concern:</strong> {Esc(e.Score.TopConcern)}</div>""");
        }
        // Surface the underlying scorer error on fallback rows so failures are diagnosable
        // from the email alone, without GitHub Actions log access.
        if (IsFallbackShape(e.Score) && !string.IsNullOrEmpty(e.Score.EligibilityReason))
        {
            sb.Append($"""<div style="margin-top:4px;font-size:11px;color:#999;"><strong>Scorer error:</strong> {Esc(e.Score.EligibilityReason)}</div>""");
        }
        sb.Append("</div>");
        return sb.ToString();
    }

    private static string Esc(string? s) => string.IsNullOrEmpty(s) ? string.Empty : WebUtility.HtmlEncode(s);

    private static bool IsFallbackShape(ScoringResult s) =>
        s.MatchScore == 1
        && s.Eligibility == EligibilityVerdict.Ambiguous
        && (s.Top3MatchedSkills is null || s.Top3MatchedSkills.Count == 0);
}
